// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl0VRL95OxpiQKrk2NuNbKiGSKXqEWuL4',
    appId: '1:123583609890:web:3cf03a65cc85ff7953de7b',
    messagingSenderId: '123583609890',
    projectId: 'tp3-planificador-viajes',
    authDomain: 'tp3-planificador-viajes.firebaseapp.com',
    storageBucket: 'tp3-planificador-viajes.firebasestorage.app',
    measurementId: 'G-405PWKSLG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMD6qFTIudqtVN1k2HCvCr1EmRcuXb648',
    appId: '1:123583609890:android:0b983ab09d78d9c153de7b',
    messagingSenderId: '123583609890',
    projectId: 'tp3-planificador-viajes',
    storageBucket: 'tp3-planificador-viajes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-4A2McbnElYFmjqhBpOC-WnxxEq8XjWY',
    appId: '1:123583609890:ios:72a312785b3e07ca53de7b',
    messagingSenderId: '123583609890',
    projectId: 'tp3-planificador-viajes',
    storageBucket: 'tp3-planificador-viajes.firebasestorage.app',
    androidClientId: '123583609890-uq9p9afcumiff6k3ndl1c4ctm7sjcdbp.apps.googleusercontent.com',
    iosClientId: '123583609890-5p1s1t2u6cb9ouktp4d8luvvcd7u8e4l.apps.googleusercontent.com',
    iosBundleId: 'com.tripplanner.tripplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-4A2McbnElYFmjqhBpOC-WnxxEq8XjWY',
    appId: '1:123583609890:ios:72a312785b3e07ca53de7b',
    messagingSenderId: '123583609890',
    projectId: 'tp3-planificador-viajes',
    storageBucket: 'tp3-planificador-viajes.firebasestorage.app',
    androidClientId: '123583609890-uq9p9afcumiff6k3ndl1c4ctm7sjcdbp.apps.googleusercontent.com',
    iosClientId: '123583609890-5p1s1t2u6cb9ouktp4d8luvvcd7u8e4l.apps.googleusercontent.com',
    iosBundleId: 'com.tripplanner.tripplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl0VRL95OxpiQKrk2NuNbKiGSKXqEWuL4',
    appId: '1:123583609890:web:3cf03a65cc85ff7953de7b',
    messagingSenderId: '123583609890',
    projectId: 'tp3-planificador-viajes',
    authDomain: 'tp3-planificador-viajes.firebaseapp.com',
    storageBucket: 'tp3-planificador-viajes.firebasestorage.app',
    measurementId: 'G-405PWKSLG9',
  );

}